# Generated by Django 5.1.5 on 2025-06-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads_images/', verbose_name='Изображение'),
        ),
    ]
